// <auto-generated />
using System;
using MediaRatingAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaRatingAPI.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    [Migration("20250402092728_Seeding")]
    partial class Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediaRatingAPI.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Medias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Format = "Film",
                            Rating = 9,
                            ReleaseDate = new DateTime(2024, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Bookworm"
                        },
                        new
                        {
                            Id = 2,
                            Format = "TV",
                            Rating = 10,
                            ReleaseDate = new DateTime(2021, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Invincible (Season 1)"
                        },
                        new
                        {
                            Id = 3,
                            Format = "Film",
                            Rating = 9,
                            ReleaseDate = new DateTime(2024, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Flow"
                        },
                        new
                        {
                            Id = 4,
                            Format = "Film",
                            Rating = 10,
                            ReleaseDate = new DateTime(2007, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hot Fuzz"
                        },
                        new
                        {
                            Id = 5,
                            Format = "TV",
                            Rating = 7,
                            ReleaseDate = new DateTime(2024, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ar y Ffin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
